### PR TITLE
Fix bugs found in V35 PJM file

### LINKED ISSUE #1536: Issue with building sys from PJM PSSE file
Using ] PowerSystems v4.6.2 `https://github.com/NREL-Sienna/PowerSystems.jl.git#psy5`
to build system from raw file with the following error. 

[ Info: Parsing PSS(R)E Two-Terminal and VSC DC line data into a PowerModels Dict...
[ Info: VSC-HVDC lines are supported via a dc line model approximated by two generators and an associated loss.
ERROR: KeyError: key "CONVERTER BUSES" not found
Stacktrace:
  [1] getindex(h::Dict{String, Any}, key::String)
    @ Base ./dict.jl:477

### PR DESCRIPTION
**Pull request by mcllerena**
- The V35 PJM files were missing the OWNER data, which were manually fixed.
- The 3w parameters were missing a conditional to be added to the ext.
- The IC data in PJM file is a bit different from the ones we've been working with, requiring an extra step to handle it with the parser.

closes #1536

### CODE REVIEW

File: src/parsers/pm_io/psse.jl [hunk 1]
```diff
@@ -2008,6 +2012,10 @@ function sort_values_by_key_prefix_v35(imp_correction::Dict{String, <:Any}, pref
         sorted_values = sorted_values[1:(length(sorted_values) - first_non_zero_index + 1)]
     end
 
+    if length(sorted_values) < 2
```
Comment (jd-lara) [inline src/parsers/pm_io/psse.jl]: where does the logic for this check come from?

Comment (mcllerena) [reply src/parsers/pm_io/psse.jl]: I updated this with more comments to explain the issue. Basically for each entry of the TIC data, a block of (0.00, 0.00, 0.00) needs to be specified to indicate the end of that entry. And for single TIC entries, the PiecewiseLinearData function_data throws an error because it needs at least two entries to define the curve, hence the conditional to skip these.

File: src/parsers/pm_io/pti.jl [hunk 2]
```diff
@@ -2096,16 +2093,12 @@ function _parse_pti_data(data_io::IO)
...
-                                re_val = parse(Float64, re_str)
-                                im_val = parse(Float64, im_str)
-
-                                if !(t_val == 0.0 && re_val == 0.0 && im_val == 0.0)
-                                    section_data_prev["T$point_index"] = t_val
-                                    section_data_prev["Re(F$point_index)"] = re_val
-                                    section_data_prev["Im(F$point_index)"] = im_val
-                                    point_index += 1
-                                end
+                                section_data_prev["T$point_index"] = parse(Float64, t_str)
```
Comment (jd-lara) [inline src/parsers/pm_io/pti.jl:2096]: What's the data you are interpolating here?

File: src/parsers/power_models_data.jl [hunk 3]
```diff
@@ -1571,18 +1575,33 @@ function make_tap_transformer(
     ext = haskey(d, "ext") ? d["ext"] : Dict{String, Any}()
     control_objective_formatter =
         get(kwargs, :transformer_control_objective_formatter, nothing)
-    control_objective =
-        if control_objective_formatter !== nothing
-            control_objective_formatter(name)
-        else
-            get(d, "COD1", -99)
-        end
+    control_objective = if control_objective_formatter !== nothing
```
Comment (jd-lara) [inline src/parsers/power_models_data.jl:1578]: is this logic correct? looks like you have the case covered with the else

File: src/parsers/pm_io/pti.jl (hunk 2 above)
Comment (mcllerena) [reply src/parsers/pm_io/pti.jl:2096]: That's specific for the "Ti" parameter of the IC data:
"_Either off-nominal turns ratio in pu of the controlling windings bus voltage base
or phase shift angle in degrees_."
I'm just looping through all entries in 3 by 3 blocks.

File: src/parsers/power_models_data.jl (hunk 3 above)
Comment (mcllerena) [reply src/parsers/power_models_data.jl:1578]: The "else" is for cases when no control objective formatter is passed, I'm just passing the formatter in case there's an undefined -99 that PSSE files does not support. 
Got this bug when testing for large cases (ERCOT/WECC/EI).
